/// Flutter icons IconsFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsFont
///      fonts:
///       - asset: fonts/IconsFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SocialIconsFont {
  SocialIconsFont._();

  static const _kFontFam = 'IconsFont';
  static const String? _kFontPkg = 'url_recognizer';

  static const IconData telegram = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
