name: url_recognizer
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    fonts:
      - family: IconsFont
        fonts:
          - asset: assets/fonts/IconsFont.ttf
